### ISSUE TITLE
Keyboard shortcuts are active in description text entry box

### ISSUE THREAD

**Issue by marnuba** [alainm23/planify#1019]
**Describe the bug**
The keyboard shortcuts are still active when the user tries to enter a description for a todo item.
For example, when the user is in the description field and enters some text, whenever she presses the 'a' key, a new todo item is added, the 's' key  creates a new section and so on.

**To Reproduce**
1. Go to any todo item
2. Click on 'Add a description'
3. Enter some text that contains one of the shortcuts keys like 'a', 's', etc.

**Expected behavior**
While entering the description the shortcuts (at least) for single letters should be disabled and the according letter should appear in the entered text.

**Desktop (please complete the following information):**
 - OS or DE: Debian Bookworm, XFCE
 - Version 4.1 according to flatpak (also Planify itself identifies as 4.0.1 in the menu)

**Additional context**
The problem is not present in the item title.

**Comment by HDInfautre** [comment]
Hi
I think I have a similar problem !
I press "A" to create a task, then I want to enter a title and a description.
As soon as I start writing, it creates another task, a section ....
I'm using ubuntu 23.04
I've installed versoin 4.0.1 flatpak

**Comment by alainm23** [comment]
I could not reproduce the bug, can you attach a reference video? and be more clear about the bug.

**Comment by HDInfautre** [comment]
See the video
in the description if I type 
"s" adds a section
"a" it adds a task
Sorry, I don't speak English very well and I'm going to bed.
Maybe the other person will explain it better?
Maybe it comes from the linux version?
[Capture vidéo du 2023-06-26 22-37-47.webm](https://github.com/alainm23/planify/assets/6817936/dc244336-6a83-43dd-a756-2262145d668c)

**Comment by Elwood4415** [comment]
I am having the same issue. It effectively prevents me from adding a task through Planify. This is on Fedora 38, with Gnome 44.2.

**Comment by PacBilly** [comment]
I'm having the same problem, also in Fedora 38 with Gnome 44.2

**Comment by aarondill** [comment]
This issue also affects me. I'm using Ubuntu 22.04.2 LTS with AwesomeWM v4.3.

**Comment by alainm23** [comment]
Fixed on v4.1.1. Update Planify pls.

**Comment by HDInfautre** [comment]
Hello
Thank you for publishing a fixed quickly.
I am not familiar with the faltpak application.
I applied "flatpak update" without seeing Planify in the list!
I still have the same problem.
In the "Planify" box, I also see version 4.0.1 displayed!
Is there anything else I can do?

_Let me ask you a side question, as I'm more used to using appimage applications, on my external disk, for this kind of application to make it portable. Where is the data: tasks, tags ... of your application?_

**Comment by alainm23** [comment]
@HDInfautre The update should arrive in a couple of hours.

Sorry, I'm not familiar with AppImage, but if someone in the community helps me distribute Planify in that format, I'm very happy.

**Comment by aarondill** [comment]
> _Let me ask you a side question, as I'm more used to using appimage applications, on my external disk, for this kind of application to make it portable. Where is the data: tasks, tags ... of your application?_ 
> 

Flatpak creates a sandbox _on your disk_ for the application. if you navigate to `~/.var/app/io.github.alainm23.planify/` you should see the sandboxed file system. Planify stores it's data in a file under `data/io.github.alainm23.planify/database.db`, which is a sqlite database containing the data.

It's difficult (but not impossible) to make edits to the data directly, however if you'd like to back up your data, simply copying this file should be sufficient (until another major schema change like 4.0 was)

**Comment by HDInfautre** [comment]
Hello
Not updated at this time 28/06
That's strange.
I made 
`flatpak update`
It updated Planify in the command line
But when I run it, I have the same problem with the "a", "s", "p" keys
And the version number marked is 4.0.1
What should I do?
Uninstall everything, but risk losing some data?

So as not to cause problems to this thread:
@aarondill 
Thank you for the information I note
@alainm23 
I've opened a suggestion https://github.com/alainm23/planify/discussions/1028

**Comment by alainm23** [comment]
Flathub Planify is in version 4.1.1, apparently there is a problem with ostree that blocks flathub updates. I heard that the community was already about to solve it, we just have to wait.

https://flathub.org/es/apps/io.github.alainm23.planify

**Comment by HDInfautre** [comment]
In fact my computer was slow, I restarted the session and everything works :-)
Thank you for your application that I will continue to test.
Thank you for your very responsive support.
I put a suggestion https://github.com/alainm23/planify/discussions/1029 , for the backup ;-)

**Comment by alainm23** [comment]
The import and export functionality is under development, JSON will be used as the format.
