### ISSUE TITLE
Planify does not launch after the 4.5 update

### ISSUE THREAD

**Issue by wada3n** [alainm23/planify#1143]
Hi, 
after 4.5 update via flatpak. Upon launching the app, it immediately closes, and an error message appears.

> ** (io.github.alainm23.planify:2): CRITICAL **: 20:11:28.121: services_cal_dav_set_credential: assertion 'message != NULL' failed
** (io.github.alainm23.planify:2): CRITICAL **: 20:11:28.777: string_to_string: assertion 'self != NULL' failed
** (io.github.alainm23.planify:2): CRITICAL **: 20:11:28.777: services_database_set_parameter_str: assertion 'val != NULL' failed
** (io.github.alainm23.planify:2): CRITICAL **: 20:11:28.777: string_to_string: assertion 'self != NULL' failed
**ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)

**Comment by alainm23** [comment]
Have you tried to log in with your Nextcloud account?

**Comment by wada3n** [comment]
I do not use Nextcloud.

**Comment by alainm23** [comment]
Did you make any backups?

**Comment by wada3n** [comment]
Hi @alainm23 ,
I had to delete and reinstall the app and lost a lot of data. Fortunately, I had taken a backup on February 3rd.

**Comment by alainm23** [comment]
I'm very sorry, I'm not sure what could have happened. The backups are a great help for this, unfortunately they are created manually, I'll see how I can get them to create automatically.

**Comment by wada3n** [comment]
Don't worry about it! I appreciate your response, and I understand that these things happen.

I'm glad to hear that you're considering implementing automatic backups. That would be a great feature.
In the meantime, I'll be more mindful of creating manual backups on a regular basis.

Thank you once again for your assistance and for developing such a fantastic application! 🙌🏼

**Comment by umgpy** [comment]
Same issue for me, but i was able to add nextcloud account. Add the same time add tasks etc.

But now planify is crashing as soon as it is opened.

OS - Fedora 39 (6.7.5-200.fc39.x86_64)

Log

```bash
$ flatpak run io.github.alainm23.planify

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 12:33:15.322: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

** (io.github.alainm23.planify:2): CRITICAL **: 12:33:15.411: objects_project_get_is_deck: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 12:33:15.411: objects_project_get_short_name: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 12:33:15.411: objects_project_get_is_deck: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 12:33:15.411: objects_project_get_is_deck: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 12:33:15.417: objects_project_get_backend_type: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 12:33:15.422: objects_project_get_is_deck: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 12:33:15.423: objects_project_get_show_completed: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 12:33:15.423: objects_project_get_show_completed: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 12:33:15.423: objects_project_get_sort_order: assertion 'self != NULL' failed

(io.github.alainm23.planify:2): GLib-GObject-CRITICAL **: 12:33:15.423: invalid (NULL) pointer instance

(io.github.alainm23.planify:2): GLib-GObject-CRITICAL **: 12:33:15.423: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(io.github.alainm23.planify:2): GLib-GObject-CRITICAL **: 12:33:15.423: invalid (NULL) pointer instance

(io.github.alainm23.planify:2): GLib-GObject-CRITICAL **: 12:33:15.423: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (io.github.alainm23.planify:2): CRITICAL **: 12:33:15.423: objects_project_get_is_deck: assertion 'self != NULL' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 12:33:15.594: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 12:33:15.594: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 12:33:15.594: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 12:33:15.594: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 12:33:15.594: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 12:33:15.594: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed
**
ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)


```

**Comment by alainm23** [comment]
@umgpy Has the bug continued to reproduce? Closing and reopening Planify does not solve the problem?

**Comment by umgpy** [comment]
@alainm23 It was solved after a reboot. I think it may have been a OS thing. Nonetheless, it only occurred once and since then I have been able to upgrade to 4.5.4 without issue.

**Comment by alainm23** [comment]
Thank you for replying

**Comment by moshiur-raj** [comment]
Planify still crashes after adding a nextcloud account in version 4.5.4. Here's the error log:

```
** (process:5612): WARNING **: 16:43:20.097: Error writing credentials to socket: Error sending message: Broken pipe

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:43:20.417: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:43:20.666: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed
**
ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
```

**Comment by ekasprzak** [comment]
I can also confirm it's still there (4.5.4):

```
**
ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
```

**Comment by alainm23** [comment]
@moshiur-raj @ekasprzak Which Nextclodu server are you using? An estimate of how many task lists and tasks you have?

**Comment by ekasprzak** [comment]
@alainm23 currently:
- NC Hub 4 (26.0.12)
- Tasks app 0.15.0
- just 3 task lists.

**Comment by alainm23** [comment]
@ekasprzak We only tested from the Nextcloud Hub 7 version, do you have a test user I could borrow?

**Comment by moshiur-raj** [comment]
@alainm23 I use https://use03.thegood.cloud and it's currently using Nextcloud 25.0.9.2
I don't have too many tasks (<50)

**Comment by moshiur-raj** [comment]
Changed my provider to https://kim.nl.tab.digital/ and planify no longer crashes. The new provider uses Nextcloud 28.0.3.2
