### ISSUE TITLE
CalDAV integration is stuck in "offline mode"

### ISSUE THREAD

**Issue by sebastiaanfranken** [alainm23/planify#1215]
**Describe the bug**
After I installed the update that fixes #1197 I now notice Planify does indeed add the CalDav server (my self-hosted Nextcloud server), but it goes into "offline" mode, and I can't figure out why or how to toggle it to "online" mode (?)

**To Reproduce**
1. Go to 'Preferences' -> 'Integrations' -> 'CalDav'
2. Click on the on/off slider and add the server
3. Add required data (username,password,server address)
3. Click 'Login'. The server is added
4. Return to the main window, and see that there is now a list called 'Nextcloud' with a refresh icon next to it. Hover over that icon to see a message that Planify has no network connection.

**Expected behavior**
Being able to add **and** user CalDav/Nextcloud

**Screenshots**
![Screenshot from 2024-03-27 15-49-42](https://github.com/alainm23/planify/assets/608882/73fadbd1-37e3-4737-a762-83a1e11fbd59)

**Desktop (please complete the following information):**
 - OS or DE: Fedora 39 (GNOME 45) Workstation, Fedora 40 (GNOME 46) Workstation Beta
 - Version: Planify 4.5.10

**Additional context**
All Planify installs are done through Flatpak (Flathub)

**Comment by sebastiaanfranken** [comment]
Going through the bug list, this is probably related to #1197

**Comment by janvlug** [comment]
My Planify did work for a while fine with my self hosted Nextcloud, but now it does not sync any more, and I see also the text that I'm working offline if I hover above the icon with the round arrows (as described in the original report above). So the difference is that synchronization did work for a while, but now stopped.

I'm using Nextcloud Hub 7 (28.0.3)

**Comment by janvlug** [comment]
I started Planify on the command line with:
`flatpak run io.github.alainm23.planify`

I synched then, and I see that each `<d:response>` element has two `<d:propstat>` elements. The first ones have a `<d:status>` of `HTTP/1.1 200 OK`, but the second ones have all a `<d:status>` of `HTTP/1.1 404 Not Found`.
<details>

	<d:response>
		<d:href>/remote.php/dav/calendars/jan/app-generated--deck--board-12/</d:href>
		<d:propstat>
			<d:prop>
				<d:resourcetype>
					<d:collection />
					<cal:calendar />
				</d:resourcetype>
				<d:displayname>Deck: Computer</d:displayname>
				<d:owner>
					<d:href>/remote.php/dav/principals/users/jan/</d:href>
				</d:owner>
				<d:current-user-privilege-set>
					<d:privilege>
						<d:write-properties />
					</d:privilege>
					<d:privilege>
						<d:read />
					</d:privilege>
					<d:privilege>
						<d:read-acl />
					</d:privilege>
					<d:privilege>
						<d:read-current-user-privilege-set />
					</d:privilege>
					<d:privilege>
						<cal:read-free-busy />
					</d:privilege>
				</d:current-user-privilege-set>
				<x1:calendar-order xmlns:x1="http://apple.com/ns/ical/">41</x1:calendar-order>
				<x1:calendar-color xmlns:x1="http://apple.com/ns/ical/">#61ac40</x1:calendar-color>
				<cal:supported-calendar-component-set>
					<cal:comp name="VTODO" />
				</cal:supported-calendar-component-set>
				<cal:supported-calendar-data>
					<cal:calendar-data content-type="text/calendar"
						version="2.0" />
					<cal:calendar-data content-type="application/calendar+json" />
				</cal:supported-calendar-data>
				<cal:max-resource-size>10000000</cal:max-resource-size>
				<cal:supported-collation-set>
					<cal:supported-collation>i;ascii-casemap</cal:supported-collation>
					<cal:supported-collation>i;octet</cal:supported-collation>
					<cal:supported-collation>i;unicode-casemap</cal:supported-collation>
				</cal:supported-collation-set>
			</d:prop>
			<d:status>HTTP/1.1 200 OK</d:status>
		</d:propstat>
		<d:propstat>
			<d:prop>
				<d:getcontenttype />
				<d:getetag />
				<d:sync-token />
				<oc:invite />
				<cs:allowed-sharing-modes />
				<cs:publish-url />
				<cs:getctag />
				<cal:calendar-description />
				<cal:calendar-timezone />
				<cal:min-date-time />
				<cal:max-date-time />
				<cal:max-instances />
				<cal:max-attendees-per-instance />
				<cal:calendar-free-busy-set />
				<cal:schedule-calendar-transp />
				<cal:schedule-default-calendar-URL />
				<oc:calendar-enabled />
				<x2:owner-displayname xmlns:x2="http://nextcloud.com/ns" />
				<x2:trash-bin-retention-duration
					xmlns:x2="http://nextcloud.com/ns" />
				<x2:deleted-at xmlns:x2="http://nextcloud.com/ns" />
				<cs:source />
				<x1:refreshrate xmlns:x1="http://apple.com/ns/ical/" />
				<cs:subscribed-strip-todos />
				<cs:subscribed-strip-alarms />
				<cs:subscribed-strip-attachments />
				<cal:calendar-availability />
			</d:prop>
			<d:status>HTTP/1.1 404 Not Found</d:status>
		</d:propstat>
	</d:response>

</details>

Maybe it is relevant that I also use the Deck app in Nextcloud. But also I see the `HTTP/1.1 404 Not Found` also in the responses for "normal" calendars.

**Comment by janvlug** [comment]
As a test, I created a new Project (this is called List in Nextcloud) in Planify. It was synched to Nextcloud, although the pop-up still stated "Offline mode is on". Then, in Nextcloud, I created a task in the project. It was not synched back to Planify. Next I created a task in Planify, this was not synched back to Nextcloud.

**Comment by sebastiaanfranken** [comment]
> I started Planify on the command line with: `flatpak run io.github.alainm23.planify`
> 
> I synched then, and I see that each `<d:response>` element has two `<d:propstat>` elements. The first ones have a `<d:status>` of `HTTP/1.1 200 OK`, but the second ones have all a `<d:status>` of `HTTP/1.1 404 Not Found`.
> 
> Maybe it is relevant that I also use the Deck app in Nextcloud. But also I see the `HTTP/1.1 404 Not Found` also in the responses for "normal" calendars.

If you don't mind my asking, how did you see the response XML stuff? Also, to be fair, I've stopped using Planify since it just doesn't work, and there are more things wrong with it. I've gone back to Errands, which "Just Works (tm)"

**Comment by alainm23** [comment]
Hello guys, the offline mode is automatic and detects if you have internet access, offline support is not yet available in Nextcloud.

**Comment by sebastiaanfranken** [comment]
> Hello guys, the offline mode is automatic and detects if you have internet access, offline support is not yet available in Nextcloud.

That's the bug part I guess, since I have internet...

**Comment by janvlug** [comment]
I can also confirm that my internet connection is functioning properly. Also the icon starts spinning, but after a while it stops spinning.
Just a guess: could it be that getting details for one specific project is resulting in an error,  and that this causes the synchronization process to break?

**Comment by janvlug** [comment]
I also noted that if I right click on a specific Project (Task list) and select Refresh from the pop up menu, there is a spinner shown for a little while for most projects. But for a few projects not.

**Comment by sebastiaanfranken** [comment]
> I can also confirm that my internet connection is functioning properly. Also the icon starts spinning, but after a while it stops spinning. Just a guess: could it be that getting details for one specific project is resulting in an error, and that this causes the synchronization process to break?

Which would be odd, since for me it also does this if I have *nothing to sync*, it never works. There is no data there in my situation to sync, as is stated I believe above.

**Comment by janvlug** [comment]
I did some further testing. And it appears to me that there are two types of Projects (Task lists) that are not updated:

1. Projects with repeating tasks
2. Projects that are bases on task related to the [Nextcloud Deck app](https://apps.nextcloud.com/apps/deck).

If it is possible to get some logging, let me know, and I will try to get it.

**Comment by janvlug** [comment]
I notice that when I changed a (repeating) task in Planify, it was still updated in Nextcloud. Even when the "offline mode" symbol is visible.
I guess that there might be some issues with specific calendars, which make the "offline mode" symbol appear.

**Comment by alainm23** [comment]
Hi guys, the sync issue has been fixed, update to 4.7.2, the offline icon is just an indication.

**Comment by craigToolBelt** [comment]
Just a quick update. I have been on 4.7.2 since it launched and I am still seeing this issue. Every time I open Planify I have to delete my sync then reconnect. It will then work properly for the entire session. As soon as I close and reopen Planify the CalDAV sync goes into offline mode again.

**Comment by alainm23** [comment]
Fixed in Planify 4.10.0
