### ISSUE TITLE
Planner does not run on startup even if "Run on startup" is activated

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#171]
However, the AppCenter applications plug correctly indicates that I want to launch the app at startup if I have previously set the switch in Planner to do so.

**Comment by alainm23** [comment]
This problem is related to: #147. And it was already resolved.

**Comment by 4jNsY6fCVqZv** [comment]
Currently does not work with version 2.1.1. **EDIT**: I use the AppCenter version.
By the way: What does the option "Run in background" mean? Unfortunately there is no explanation in the settings. Do I need to enable it, so that the option "Run on startup" also works?

**Comment by WebShapedBiz** [comment]
I'm sorry to report but version 2.1.1. is still not launching at startup.
@4jNsY6fCVqZv this option means that it doesn't pop up on the desktop when it starts, instead, it runs minimized in Plank. That's cool feature to have.

**Comment by 4jNsY6fCVqZv** [comment]
@WebShapedBiz Thank you for the explanation!
Does this only work during system startup if "Run on startup" and "Run in background" have been enabled simultaneously before?
I just tried the following now:
"Run in background" -> activated.
"Run on startup" -> disabled.
But Planner starts normally in the window, unfortunately not minimized.

**Comment by alainm23** [comment]
**Run in background:** This feature causes Planner to run in the background when it is closed, with the intention of updating itself and sending notifications (reminders)

**Run on startup:** This feature causes Planner to start with the system with the intention of updating itself and sending notifications (reminders)

**Comment by alainm23** [comment]
@WebShapedBiz Did you install Planner from AppCenter or Flathub?

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 Do you think it makes sense that your explanation appears in the settings menu for these options? Perhaps these are not always self-explanatory.

**EDIT**: After your explanation, I can say: the "Run in background" feature works!

**Comment by alainm23** [comment]
Sure 😉️.

**Comment by WebShapedBiz** [comment]
@alainm23 from the AppCenter.

**Comment by alainm23** [comment]
You probably need to turn the switch off and on again for this to work.

**Comment by WebShapedBiz** [comment]
@alainm23 you were right, now everything works :-)

**Comment by 4jNsY6fCVqZv** [comment]
Oh okay, I tried https://github.com/alainm23/planner/issues/171#issuecomment-580882608 again.
My expectation was that Planner would open a window in the foreground every time I log into my desktop.
Now that I really had an event for today, I immediately saw a badge with "1". And when I open Planner, the badge disappears again. That's how it's supposed to be, right?
