### ISSUE TITLE
No tasks synced with Mailbox CalDAV service (mailbox.org)

### ISSUE THREAD

**Issue by tqcharm** [alainm23/planify#2018]
**Description**
No tasks are synced when setting up CalDAV sync with Mailbox service (mailbox.org). However, the connection is established, given that task lists (*Projects* in _Planify_) are being synced.

**To Reproduce**
1. Make sure you have an active Mailbox account.
2. Create tasks in *Mailbox*'s web interface.
3. Set up CalDAV synchronization with your *Mailbox* account.
4. Check synchronization in _Planify_ with *Mailbox* tasks.
5. Create tasks in the Mailbox account area in _Planify_.
6. Check that tasks created locally are snyced with *Mailbox*.

**Expected behavior**
Both tasks created in *Mailbox*'s web interface, as well as tasks created in _Planify_ are being synced on both ends.

**Actual behavior**
No tasks are synced from *Mailbox* service (from server to local). Tasks created locally (from local to server) are being synced.

**Desktop (please complete the following information):**
 - OS or DE: Fedora Silverblue 43 with GNOME 49
 - Planify Version: 4.15.2 (Flatpak from Flathub).

**Comment by themagiulio** [comment]
I was about to report the same issue. When I set up CalDAV synchronization with my Mailbox account, I cannot see previously added task, however, I can add tasks that I can then see on Mailbox's web interface. If I try to complete a task an error occurs with the following message:

```
PUT https://dav.mailbox.org/caldav/MzM//<SOME-IDENTIFIER>.ics failed: HTTP 201 Created
``` 

If needed, I could provide other details you may need to debug.

**Comment by tqcharm** [comment]
I have somehow overlooked that tasks created in Planify are actually synced to the Mailbox server (it's only those on Mailbox's account that are not synced locally).  I have updated the issue description. Thanks for the hint @themagiulio .

**Comment by balupton** [comment]
I can't seem to connect it, created a caldav app password, and tried `https://mailbox.org` as the server, which gave a long error message in planify, and then tried the usual `https://dav.mailbox.org` which just gave the error message of `.`

Here's the long error message of `https://mailbox.org`

```
Failed to resolve calendar home: Failed to resolve calendar home: PROPFIND https://auto.mailbox.org/.well-known/caldav failed: HTTP 405 Method Not Allowed
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Method not allowed!</title>
<link rev="made" href="mailto:support@mailbox.org" />
<style type="text/css"><!--/*--><![CDATA[/*><!--*/ 
    body { color: #000000; background-color: #FFFFFF; }
    a:link { color: #0000CC; }
    p, address {margin-left: 3em;}
    span {font-size: smaller;}
/*]]>*/--></style>
</head>

<body>
<h1>Method not allowed!</h1>
<p>


    The PROPFIND
    method is not allowed for the requested URL.
    
</p>
<p>
If you think this is a server error, please contact
the <a href="mailto:support@mailbox.org">webmaster</a>.

</p>

<h2>Error 405</h2>
<address>
  <a href="/">auto.mailbox.org</a><br />
  <span>Apache</span>
</address>
</body>
</html>
```

Pity that reading the earlier messages above it seems that planify can't auto-sync the various mailbox task lists.

**Comment by alainm23** [comment]
Thanks for the detailed report! This should be fixed in the upcoming release as part of PR #2368, which includes:

- Fallback to full fetch when `sync-collection` is not supported, fixing incoming sync from the server
- Better handling of non-standard HTTP responses from CalDAV servers

This will be released this weekend. Please update and let us know if the issue persists!

**Comment by tqcharm** [comment]
Thanks for working on this issue. I have tested it on version *4.19.0* (Flatpak from Flathub), and the issue still reproduces for service `mailbox.org`. Tasks created locally (*Planify*) are sync with the server, but tasks created using *mailbox*'s webapp interface are not fetched by *Planify*.

**Comment by tqcharm** [comment]
Working in version _4.19.1_.

**Comment by tqcharm** [comment]
Hey! This issue has regressed in version *4.19.2*.

**Comment by alainm23** [comment]
Hi,

Thank you for reporting the regression! We didn't make direct changes to the core CalDAV sync logic in 4.19.2, so this is unexpected and we'd like to investigate.

Could you share the Planify logs from a sync attempt? You can find them at:

`~/.var/app/io.github.alainm23.planify/data/io.github.alainm23.planify/logs/`

That will help us pinpoint exactly where the sync is failing. Thanks!

**Comment by tqcharm** [comment]
Sure. Below are some excerpts from the logs (previous and current patch). In the latest version the fallback to ETag sync seems to be missing.

Version *4.19.1*
```
[2026-05-14 21:37:35] [INFO] [TimeMonitor] Initialized, tracking date: 2026-05-14
[2026-05-14 21:37:35] [INFO] [TimeMonitor] Next day check scheduled in 8544 seconds
[2026-05-14 21:37:35] [INFO] [TimeMonitor] Subscribed to ScreenSaver WakeUpScreen signal
[2026-05-14 21:37:38] [INFO] [Source] Starting sync server for source: Mailbox
[2026-05-14 21:37:38] [INFO] [CalDAV.Core] Starting sync
[2026-05-14 21:37:38] [INFO] [CalDAV.Core] Creating new client for source
[2026-05-14 21:37:38] [INFO] [CalDAV] Syncing project list
[2026-05-14 21:37:38] [DEBUG] [WebDAV] PROPFIND request (depth: 1)
[2026-05-14 21:37:38] [DEBUG] [WebDAV] PROPFIND https://dav.mailbox.org/caldav/
[2026-05-14 21:37:38] [DEBUG] [CalDAV.Core] Found 4 projects to sync
[2026-05-14 21:37:38] [DEBUG] [CalDAV.Core] Project: 'Tasks' | sync_id: '1777292787221' | url: 'https://dav.mailbox.org/caldav/MzM/'
[2026-05-14 21:37:38] [INFO] [CalDAV] Syncing tasklist
[2026-05-14 21:37:38] [DEBUG] [CalDAV] Fetching project details
[2026-05-14 21:37:38] [DEBUG] [WebDAV] PROPFIND request (depth: 1)
[2026-05-14 21:37:38] [DEBUG] [WebDAV] PROPFIND https://dav.mailbox.org/caldav/MzM/
[2026-05-14 21:37:38] [DEBUG] [CalDAV] sync_id after fetch_project_details: '1777292787221'
[2026-05-14 21:37:38] [DEBUG] [WebDAV] REPORT request (depth: 1)
[2026-05-14 21:37:38] [DEBUG] [WebDAV] REPORT https://dav.mailbox.org/caldav/MzM/
[2026-05-14 21:37:38] [ERROR] [WebDAV] REPORT https://dav.mailbox.org/caldav/MzM/ failed: HTTP 400 Bad Request
[2026-05-14 21:37:38] [WARNING] [CalDAV] sync-collection failed, falling back to ETag sync: REPORT https://dav.mailbox.org/caldav/MzM/ failed: HTTP 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<D:error xmlns:D="DAV:" xmlns:OX="http://ox.io/ns/">
  <OX:error>An error occurred inside the server which prevented it from fulfilling the request.</OX:error>
  <OX:category>ERROR</OX:category>
  <OX:code>WEBDAV-1000</OX:code>
  <OX:error_id>-1481730126-20020447</OX:error_id>
  <OX:error_desc>A WebDAV error occurred. (HTTP 400)</OX:error_desc>
</D:error>

[2026-05-14 21:37:38] [INFO] [CalDAV] ETag sync for 'Tasks'
[2026-05-14 21:37:38] [DEBUG] [WebDAV] REPORT request (depth: 1)
[2026-05-14 21:37:38] [DEBUG] [WebDAV] REPORT https://dav.mailbox.org/caldav/MzM/
[2026-05-14 21:37:39] [DEBUG] [CalDAV] Project has 119 items
[...]
```

Version *4.19.2*
```
[2026-05-14 22:00:44] [INFO] [TimeMonitor] Initialized, tracking date: 2026-05-14
[2026-05-14 22:00:44] [INFO] [TimeMonitor] Next day check scheduled in 7155 seconds
[2026-05-14 22:00:44] [INFO] [TimeMonitor] Subscribed to ScreenSaver WakeUpScreen signal
[2026-05-14 22:00:47] [INFO] [Source] Starting sync server for source: Mailbox
[2026-05-14 22:00:47] [INFO] [CalDAV.Core] Starting sync
[2026-05-14 22:00:47] [INFO] [CalDAV.Core] Creating new client for source
[2026-05-14 22:00:47] [INFO] [CalDAV] Syncing project list
[2026-05-14 22:00:47] [DEBUG] [WebDAV] PROPFIND request (depth: 1)
[2026-05-14 22:00:47] [DEBUG] [WebDAV] PROPFIND https://dav.mailbox.org/caldav/
[2026-05-14 22:00:48] [DEBUG] [CalDAV.Core] Found 4 projects to sync
[2026-05-14 22:00:48] [DEBUG] [CalDAV.Core] Project: 'Tasks' | sync_id: '1778768683868' | url: 'https://dav.mailbox.org/caldav/MzM/'
[2026-05-14 22:00:48] [INFO] [CalDAV] Syncing tasklist
[2026-05-14 22:00:48] [DEBUG] [CalDAV] Fetching project details
[2026-05-14 22:00:48] [DEBUG] [WebDAV] PROPFIND request (depth: 1)
[2026-05-14 22:00:48] [DEBUG] [WebDAV] PROPFIND https://dav.mailbox.org/caldav/MzM/
[2026-05-14 22:00:48] [DEBUG] [CalDAV] sync_id after fetch_project_details: '1778768683868'
[2026-05-14 22:00:48] [DEBUG] [WebDAV] REPORT request (depth: 1)
[2026-05-14 22:00:48] [DEBUG] [WebDAV] REPORT https://dav.mailbox.org/caldav/MzM/
[...]
```

**Comment by byquanton** [comment]
In 4.19.1 sync-collection was broken, this was fixed in 4.19.2 with
https://github.com/alainm23/planify/pull/2423/changes/3c88ba934cd27905a9aaadb7f270efc49b488279

**Comment by byquanton** [comment]
Notes while debugging sync with mailbox:

---

With the regression, which broke sync-collection based sync in v4.19.1. The etag solution bypassed the following two bugs:


---

The response from mailbox to the initial report request in `fetch_items_for_project` wraps the calendar data inside CDATA. Planify isn't receiving the `vtodo_content` because `calendar_data.text_content` is null when CDATA is present. 

<details>
<summary>Raw Response Data</summary>

```
HTTP/2.0 207 
x-powered-by: Open-Xchange
date: Thu, 14 May 2026 20:49:46 GMT
content-type: text/xml; charset=UTF-8
feature-policy: accelerometer 'none'; camera 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; usb 'none';
referrer-policy: no-referrer
strict-transport-security: max-age=15552000; includeSubDomains; preload;
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
x-robots-tag: noindex, nofollow
x-xss-protection: 1; mode=block
vary: Accept-Encoding
content-length: 4231

<?xml version="1.0" encoding="UTF-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:APPLE="http://apple.com/ns/ical/" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/">
  <D:response>
    <D:href>/caldav/MzU/a098527c-be33-475a-8156-ecf949a6fcd8.ics</D:href>
    <D:propstat>
      <D:prop>
        <D:getetag>2455257-1-1778791068597</D:getetag>
        <D:displayname />
        <D:getcontenttype>text/calendar; charset=UTF-8</D:getcontenttype>
        <D:resourcetype />
        <calendar-data xmlns="urn:ietf:params:xml:ns:caldav"><![CDATA[BEGIN:VCALENDAR
PRODID:Open-Xchange
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VTODO
DTSTAMP:20260514T204946Z
SUMMARY:Test 1234
DESCRIPTION:test
CLASS:PUBLIC
STATUS:NEEDS-ACTION
PRIORITY:5
UID:a098527c-be33-475a-8156-ecf949a6fcd8
CREATED:20260514T203748Z
LAST-MODIFIED:20260514T203748Z
END:VTODO
END:VCALENDAR]]></calendar-data>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
    <D:propstat>
      <D:prop>
        <D:current-user-privilege-set />
        <D:owner />
        <D:sync-token />
      </D:prop>
      <D:status>HTTP/1.1 404 NOT FOUND</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/MzU/25fe3ac1-e14c-4c94-bbb1-9589cdc0ccbf.ics</D:href>
    <D:propstat>
      <D:prop>
        <D:getetag>2455257-2-1778791083398</D:getetag>
        <D:displayname />
        <D:getcontenttype>text/calendar; charset=UTF-8</D:getcontenttype>
        <D:resourcetype />
        <calendar-data xmlns="urn:ietf:params:xml:ns:caldav"><![CDATA[BEGIN:VCALENDAR
PRODID:Open-Xchange
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VTODO
DTSTAMP:20260514T204946Z
SUMMARY:second task
CLASS:PUBLIC
STATUS:NEEDS-ACTION
PRIORITY:5
UID:25fe3ac1-e14c-4c94-bbb1-9589cdc0ccbf
CREATED:20260514T203803Z
LAST-MODIFIED:20260514T203803Z
END:VTODO
END:VCALENDAR]]></calendar-data>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
    <D:propstat>
      <D:prop>
        <D:current-user-privilege-set />
        <D:owner />
        <D:sync-token />
      </D:prop>
      <D:status>HTTP/1.1 404 NOT FOUND</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/MzU/5da68faf-3a3e-4f23-b20d-b3ad13ceae2c.ics</D:href>
    <D:propstat>
      <D:prop>
        <D:getetag>2455257-4-1778791134500</D:getetag>
        <D:displayname />
        <D:getcontenttype>text/calendar; charset=UTF-8</D:getcontenttype>
        <D:resourcetype />
        <calendar-data xmlns="urn:ietf:params:xml:ns:caldav"><![CDATA[BEGIN:VCALENDAR
PRODID:Open-Xchange
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VTODO
DTSTAMP:20260514T204946Z
SUMMARY:Task in mailbox interface
CLASS:PUBLIC
STATUS:NEEDS-ACTION
PERCENT-COMPLETE:0
UID:5da68faf-3a3e-4f23-b20d-b3ad13ceae2c
CREATED:20260514T203854Z
LAST-MODIFIED:20260514T203854Z
END:VTODO
END:VCALENDAR]]></calendar-data>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
    <D:propstat>
      <D:prop>
        <D:current-user-privilege-set />
        <D:owner />
        <D:sync-token />
      </D:prop>
      <D:status>HTTP/1.1 404 NOT FOUND</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/MzU/5589e5c1-9b28-4e10-98be-4f572646e4af.ics</D:href>
    <D:propstat>
      <D:prop>
        <D:getetag>2455257-5-1778791493163</D:getetag>
        <D:displayname />
        <D:getcontenttype>text/calendar; charset=UTF-8</D:getcontenttype>
        <D:resourcetype />
        <calendar-data xmlns="urn:ietf:params:xml:ns:caldav"><![CDATA[BEGIN:VCALENDAR
PRODID:Open-Xchange
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VTODO
DTSTAMP:20260514T204946Z
SUMMARY:aaaa
CLASS:PUBLIC
STATUS:NEEDS-ACTION
PRIORITY:5
UID:5589e5c1-9b28-4e10-98be-4f572646e4af
CREATED:20260514T204453Z
LAST-MODIFIED:20260514T204453Z
END:VTODO
END:VCALENDAR]]></calendar-data>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
    <D:propstat>
      <D:prop>
        <D:current-user-privilege-set />
        <D:owner />
        <D:sync-token />
      </D:prop>
      <D:status>HTTP/1.1 404 NOT FOUND</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>
```
</details>

With a quick and dirty substring hack I managed to get the initial sync working, subsequent syncs still fail.

---

In subsequent requests Planify checks the contenttype if it contains "VTODO"

https://github.com/alainm23/planify/blob/55e75fb0fc6d602e91c12b521520ac6890a552ec/core/Services/CalDAV/CalDAVClient.vala#L445-L460

The RFC (https://datatracker.ietf.org/doc/html/rfc5545#section-8.1) lists "component" as an optional parameter.

So the response from Open-Xchange/mailbox is RFC compliant, but annoying
 `<D:getcontenttype>text/calendar; charset=UTF-8</D:getcontenttype>`


<details>
<summary>Raw Response Data</summary>

```
HTTP/2.0 207 
x-powered-by: Open-Xchange
date: Thu, 14 May 2026 22:07:26 GMT
content-type: text/xml; charset=UTF-8
feature-policy: accelerometer 'none'; camera 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; usb 'none';
referrer-policy: no-referrer
strict-transport-security: max-age=15552000; includeSubDomains; preload;
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
x-robots-tag: noindex, nofollow
x-xss-protection: 1; mode=block
vary: Accept-Encoding
content-length: 612

<?xml version="1.0" encoding="UTF-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:APPLE="http://apple.com/ns/ical/" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/">
  <D:response>
    <D:href>/caldav/MzU/6f33c44c-4fc2-49ef-b85f-a2664b5477bb.ics</D:href>
    <D:propstat>
      <D:prop>
        <D:getetag>2455257-9-1778796441497</D:getetag>
        <D:getcontenttype>text/calendar; charset=UTF-8</D:getcontenttype>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
  <D:sync-token>1778796441497</D:sync-token>
</D:multistatus>
```
</details>

**Comment by byquanton** [comment]
Test Build: [planify.Devel-x86_64.flatpak](https://github.com/alainm23/planify/actions/runs/25890894828/artifacts/7006879105)
