### ISSUE TITLE
Not updating day when running in background

### ISSUE THREAD

**Issue by kd2flz** [alainm23/planify#534]
I'm running planner on Pop-os. When I leave it running overnight, it doesn't "automatically" change to the next day.

**To Reproduce**
1. Leave Planner open overnight
2. Go to "today"
3. It still shows yesterday's tasks and date

**Expected behavior**
It should automatically change to the next day when I leave it running in the background overnight.

**Pop-OS**
 - Gnome 
 - 3.36.3

**Comment by alainm23** [comment]
This error is already fixed in the master, please wait for the new update.

**Comment by kd2flz** [comment]
Thanks! That's awesome.

**Comment by rzelnik** [comment]
I confirm that this issue still occurs in version 2.6.2. My system: Ubuntu 20.10, Planner installed through Flatpak.

**Comment by twrightsman** [comment]
I can also confirm this is an issue in version 2.6.9, I just saw this behavior again this morning.
